FROM node:11-alpine
COPY / /app
WORKDIR /app
ENV SPARK_HOST=hdcpx02.interno
ENV MONGO=localhost://mongo:27017
ENV MONGO_USER=notebook
ENV MONGO_PASSWORD=burning-book
ENV USER_BLACKLIST=
ENV SPARK_QUEUE=
ENV SPARK_LIBRARIES=
EXPOSE 9085
CMD node index.js
